# This is a basic workflow to help you get started with Act
<!DOCTYPE html>
<html>
<head>
    <title>منصة الطلاب</title>
</head>
<body>
    <header>
        <h1>منصة الطلاب</h1>
    </header>

    <section id="publish">
        <h2>نشر تقرير أو مقالة</h2>
        <form action="process.php" method="post" enctype="multipart/form-data">
            <label for="title">العنوان:</label>
            <input type="text" id="title" name="title" required><br><br>

            <label for="content">المحتوى:</label><br>
            <textarea id="content" name="content" rows="5" cols="40" required></textarea><br><br>

            <label for="file">ارفع الملف (إذا كان ذلك مناسبًا):</label>
            <input type="file" id="file" name="file"><br><br>

            <input type="submit" value="نشر">
        </form>
    </section>

    <section id="articles">
        <h2>المقالات والتقارير</h2>
        <!-- هنا 
</html>
```


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
